# Generated by Django 5.0.2 on 2024-02-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_country_provider_provider_tag_furniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='tags',
        ),
    ]
