# Generated by Django 5.0.2 on 2024-02-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tasks_remove_furniture_country_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(max_length=225, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Title'),
        ),
    ]
